use std::collections::HashMap;

static PAD: &str = "_"; //padding (0)
static BOS: &str = "^"; //beginning of sentence
static EOS: &str = "$"; //end of sentence

pub fn phonemes_to_ids(phonemes: &String, id_map: Option<&HashMap<String, i64>>) -> Vec<i64> {
    let id_map = ensure_phoneme_id_map(id_map);
    let mut phone_ids = vec![id_map[&BOS.to_string()], id_map[&PAD.to_string()]];

    for phon in phonemes.chars() {
        phone_ids.push(id_map[&phon.to_string()]);
        phone_ids.push(id_map[&PAD.to_string()]);
    }
    phone_ids.push(id_map[&EOS.to_string()]);
    phone_ids
}

fn ensure_phoneme_id_map(id_map: Option<&HashMap<String, i64>>) -> HashMap<String, i64> {
    match id_map {
        Some(map) => map.clone(),
        None => HashMap::from([
            ("_".into(), 0),
            ("^".into(), 1),
            ("$".into(), 2),
            (" ".into(), 3),
            ("!".into(), 4),
            ("'".into(), 5),
            ("(".into(), 6),
            (")".into(), 7),
            (",".into(), 8),
            ("-".into(), 9),
            (".".into(), 10),
            (":".into(), 11),
            (";".into(), 12),
            ("?".into(), 13),
            ("a".into(), 14),
            ("b".into(), 15),
            ("c".into(), 16),
            ("d".into(), 17),
            ("e".into(), 18),
            ("f".into(), 19),
            ("h".into(), 20),
            ("i".into(), 21),
            ("j".into(), 22),
            ("k".into(), 23),
            ("l".into(), 24),
            ("m".into(), 25),
            ("n".into(), 26),
            ("o".into(), 27),
            ("p".into(), 28),
            ("q".into(), 29),
            ("r".into(), 30),
            ("s".into(), 31),
            ("t".into(), 32),
            ("u".into(), 33),
            ("v".into(), 34),
            ("w".into(), 35),
            ("x".into(), 36),
            ("y".into(), 37),
            ("z".into(), 38),
            ("æ".into(), 39),
            ("ç".into(), 40),
            ("ð".into(), 41),
            ("ø".into(), 42),
            ("ħ".into(), 43),
            ("ŋ".into(), 44),
            ("œ".into(), 45),
            ("ǀ".into(), 46),
            ("ǁ".into(), 47),
            ("ǂ".into(), 48),
            ("ǃ".into(), 49),
            ("ɐ".into(), 50),
            ("ɑ".into(), 51),
            ("ɒ".into(), 52),
            ("ɓ".into(), 53),
            ("ɔ".into(), 54),
            ("ɕ".into(), 55),
            ("ɖ".into(), 56),
            ("ɗ".into(), 57),
            ("ɘ".into(), 58),
            ("ə".into(), 59),
            ("ɚ".into(), 60),
            ("ɛ".into(), 61),
            ("ɜ".into(), 62),
            ("ɞ".into(), 63),
            ("ɟ".into(), 64),
            ("ɠ".into(), 65),
            ("ɡ".into(), 66),
            ("ɢ".into(), 67),
            ("ɣ".into(), 68),
            ("ɤ".into(), 69),
            ("ɥ".into(), 70),
            ("ɦ".into(), 71),
            ("ɧ".into(), 72),
            ("ɨ".into(), 73),
            ("ɪ".into(), 74),
            ("ɫ".into(), 75),
            ("ɬ".into(), 76),
            ("ɭ".into(), 77),
            ("ɮ".into(), 78),
            ("ɯ".into(), 79),
            ("ɰ".into(), 80),
            ("ɱ".into(), 81),
            ("ɲ".into(), 82),
            ("ɳ".into(), 83),
            ("ɴ".into(), 84),
            ("ɵ".into(), 85),
            ("ɶ".into(), 86),
            ("ɸ".into(), 87),
            ("ɹ".into(), 88),
            ("ɺ".into(), 89),
            ("ɻ".into(), 90),
            ("ɽ".into(), 91),
            ("ɾ".into(), 92),
            ("ʀ".into(), 93),
            ("ʁ".into(), 94),
            ("ʂ".into(), 95),
            ("ʃ".into(), 96),
            ("ʄ".into(), 97),
            ("ʈ".into(), 98),
            ("ʉ".into(), 99),
            ("ʊ".into(), 100),
            ("ʋ".into(), 101),
            ("ʌ".into(), 102),
            ("ʍ".into(), 103),
            ("ʎ".into(), 104),
            ("ʏ".into(), 105),
            ("ʐ".into(), 106),
            ("ʑ".into(), 107),
            ("ʒ".into(), 108),
            ("ʔ".into(), 109),
            ("ʕ".into(), 110),
            ("ʘ".into(), 111),
            ("ʙ".into(), 112),
            ("ʛ".into(), 113),
            ("ʜ".into(), 114),
            ("ʝ".into(), 115),
            ("ʟ".into(), 116),
            ("ʡ".into(), 117),
            ("ʢ".into(), 118),
            ("ʲ".into(), 119),
            ("ˈ".into(), 120),
            ("ˌ".into(), 121),
            ("ː".into(), 122),
            ("ˑ".into(), 123),
            ("˞".into(), 124),
            ("β".into(), 125),
            ("θ".into(), 126),
            ("χ".into(), 127),
            ("ᵻ".into(), 128),
            ("ⱱ".into(), 129),
            ("0".into(), 130),
            ("1".into(), 131),
            ("2".into(), 132),
            ("3".into(), 133),
            ("4".into(), 134),
            ("5".into(), 135),
            ("6".into(), 136),
            ("7".into(), 137),
            ("8".into(), 138),
            ("9".into(), 139),
            ("̧".into(), 140),
            ("̃".into(), 141),
            ("̪".into(), 142),
            ("̯".into(), 143),
            ("̩".into(), 144),
            ("ʰ".into(), 145),
            ("ˤ".into(), 146),
            ("ε".into(), 147),
            ("↓".into(), 148),
            ("#".into(), 149),
            ("\"".into(), 150),
            ("↑".into(), 151),
            ("̺".into(), 152),
            ("̻".into(), 153),
            ("g".into(), 154),
            ("ʦ".into(), 155),
            ("X".into(), 156),
            ("̝".into(), 157),
            ("̊".into(), 158),
            ("ɝ".into(), 159),
            ("ʷ".into(), 160),
        ]),
    }
}
